#! /bin/bash
while IFS= read -r line; do
    [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
    export "$line"
done < "$PWD/.env"
docker exec -it $(docker ps --format '{{.Names}}' | grep $PROJECT_NAME | grep '^web') bash
